carts/urls.py
from django.urls import path
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
)

urlpatterns = [
    path('', cart_home, name="home"),
    path('checkout/success/', checkout_done_view, name="success"),
    path('checkout/', checkout_home, name="checkout"),
    path('update/', cart_update, name="update"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view
from accounts.views import(
    register_view,
    login_view,
    guest_register_view
)
from .views import (
    home_view,
    contact_view,
    about_view,
)

urlpatterns = [
    path('', home_view, name="home"),
    path('about/', about_view, name="about"),
    path('contact/', contact_view, name="contact"),
    path('login/', login_view, name="login"),
    path('api/cart/', cart_detail_api_view, name="api-cart"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', register_view, name="register"),
    path('checkout/address/create/', checkout_address_create_view, name="checkout_address_create"),
    path('checkout/address/reuse/', checkout_address_reuse_view, name="checkout_address_reuse"),
    path('register/guest', guest_register_view, name="guest_register"),
    path('cart/', include(('carts.urls', "carts"), namespace="cart")),
    path('products/', include(('products.urls', "products"), namespace="products")),
    path('search/', include(('search.urls', "search"), namespace="search")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import (
    ProductListView,
    ProductDetailView,
    # ProducFeaturedtListView,
    # ProductFeaturedDetailView,
)

urlpatterns = [
    path('', ProductListView.as_view(), name="list"),
    # path('featured/', ProducFeaturedtListView.as_view()),
    path('<slug>/', ProductDetailView.as_view(), name="detail"),
    # path('featured/<slug>/', ProductFeaturedDetailView.as_view()),
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!-- fontawesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as products_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:update' as cart_url %}




<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{ brand_name }} {% else %} Brand Name
            {% endif %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %}active{%endif%}">
                    <a class="nav-link" href="{{ home_url }}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == products_url %}active{%endif%}">
                    <a class="nav-link" href="{{ products_url }}">products</a>
                </li>
                <li class="nav-item {% if request.path == contact_url %}active{%endif%}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == about_url %}active{%endif%}">
                    <a class="nav-link" href="{{ about_url }}">about</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item {% if request.path == logout_url %}active{%endif%}">
                    <a class="nav-link" href="{{ logout_url }}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item {% if request.path == login_url %}active{%endif%}">
                    <a class="nav-link" href="{{ login_url }}">Login</a>
                </li>
                <li class="nav-item {% if request.path == register_url %}active{%endif%}">
                    <a class="nav-link" href="{{ register_url }}">Register</a>
                </li>
                {% endif %}
                <li class="nav-item {% if request.path == cart_url %}active{%endif%}">
                    <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fas fa-shopping-cart"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            {% include "search/snippets/search.html" %}
        </div>
    </div>
</nav>